<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE5jlozx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE5jlozx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerE5jlozx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerE5jlozx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerE5jlozx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'E5jlozx',
    'container.build_id' => '3b6a418c',
    'container.build_time' => 1574461213,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerE5jlozx');
